# Generated by Django 4.1.2 on 2022-10-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crud",
            name="TOTAL_FORMS",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crud",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
